# PowerShellGraph-CopyItemToAnotherMailbox.ps1
# This will copy the specified item from one user's mailbox to another user's Inbox.
#
# Example usage:
# cd C:\powersehell
# powershell -File PowerShellGraph-CopyItemToAnotherMailbox.ps1 -TenantId "dd55b8f6-4d6e-xxxx-8982-xxxx" -ClientId "ed005ff1-b5c2-xxxx-a9d2-xxxxxxx" -ClientSecret "kg58Q~sxKM5MU2222ldxdIWlg1234xyzCMKpbAh" -SourceUser "user1@contoso.onmicrosoft.com" -SourceItemId "AAMkAGEyMTcxMWI4LWEyYzAtNGI1Mi05ZjYyLTQ0YzE1ZjI3NWE3ZgBGAAAAAADQo-ItsAnInterestingGraphIdwC1z1oWxpmiTIh5q-oL-wAiAAAAAAEMAAC1z1oWxpmiTIh5q-oL-123456789=" -DestUser "user2@contoso.onmicrosoft.com"    
#
# Note: The above example uses placeholder values; replace with actual tenant/app/user/item IDs and secrets.
# Code initially generated by Microsoft Copilot based on Graph API docs.
# Last tested this script on 2/12/2026 with PowerShell 7.2+ and Graph beta APIs as of mid-2024. 
# Please review and test before using in production and remember this is just an information sample and you are responsible for using it as it will be yoru code upon ussage.
# You can get an item Id using Graph Explorer or other Graph API tools.  Consider trying this sample to get a message Id: https://github.com/dseph/Ews-PowerShell-Appflow-ListFirstThreeEmails

<# 
.SYNOPSIS
  Export one email from a source mailbox using the Graph Mailbox Export API (beta) and import it
  into the Inbox of another mailbox using the Mailbox Import API (beta).
  Please note that Preview APIs are subject to change, and should be used with test mailboxes. There is no mainline support for these APIs yet.

.PARAMETER TenantId
  Entra ID tenant ID (GUID)

.PARAMETER ClientId
  App (client) ID of your Entra application

.PARAMETER ClientSecret
  Client secret for the app (client credentials flow)

.PARAMETER SourceUser
  UPN of the source mailbox (e.g., alice@contoso.com)

.PARAMETER SourceItemId
  The item ID to export. For most scenarios, pass the Graph message Id for the email you want to move.
  (The Export API expects a mailboxItem id; Graph message Ids work for items under the IPM subtree.)

.PARAMETER DestUser
  UPN of the destination mailbox (e.g., bob@contoso.com)

.PARAMETER DestFolderId
  Optional. Destination folder Id in the destination mailbox. If omitted, script resolves the Inbox by name.
  
Permissions:
  - Application permissions required: MailboxSettings.Read for resolving mailbox ids, and MailboxExport/Import for the export/import operations. Admin consent required.
Notes:
  - The export/import APIs are in beta and may change. Use with test mailboxes.
    - The script assumes the item being moved is an email message, but the APIs also support other mailbox items (events, contacts, etc.) with appropriate adjustments.
    - The exported data is a base64-encoded FTS stream, which is opaque to clients. The same stream is ingested by the import API to recreate the item in the destination mailbox.
    - Error handling is minimal for brevity; production code should handle potential errors and edge cases more robustly.

.EXAMPLE

    .\CopyItemToAnotherMailbox.ps1 -TenantId "your-tenant-id" -ClientId "your-app-id" -ClientSecret "your-app-secret" -SourceUser "alice@contoso.com" -SourceItemId "AAMkADU5ZjYxYzIyLWQxYjctNDI2Zi1hMzQ0LWUwNjE2Mzg4ZmE0YwBGAAAAAACJ7X8c7X8c7X8c7X8c7X8c7X8c7X8c7X8c7X8c7X8c7X8c7X8c7X8c7X8c7X8=" -DestUser "bob@contoso.com"

Permission:
    App‑only permissions required (grant admin consent):
    MailboxItem.Export.All (or MailboxItem.ImportExport.All) for export,
    MailboxItem.ImportExport.All for import,
    MailboxFolder.Read.All to discover folders,
    User.Read.All to resolve the mailbox id via user exchange settings.
#>

param(
  [Parameter(Mandatory=$true)] [string] $TenantId,
  [Parameter(Mandatory=$true)] [string] $ClientId,
  [Parameter(Mandatory=$true)] [string] $ClientSecret,
  [Parameter(Mandatory=$true)] [string] $SourceUser,
  [Parameter(Mandatory=$true)] [string] $SourceItemId,
  [Parameter(Mandatory=$true)] [string] $DestUser,
  [string] $DestFolderId
)

$ErrorActionPreference = 'Stop'
$graph = "https://graph.microsoft.com"

function Get-GraphToken {
  param([string]$TenantId,[string]$ClientId,[string]$ClientSecret)
  $body = @{
    client_id     = $ClientId
    client_secret = $ClientSecret
    scope         = "https://graph.microsoft.com/.default"
    grant_type    = "client_credentials"
  }
  $resp = Invoke-RestMethod -Method POST -Uri "https://login.microsoftonline.com/$TenantId/oauth2/v2.0/token" -Body $body -ContentType "application/x-www-form-urlencoded"
  return $resp.access_token
}

function Invoke-GraphJson {
  param(
    [Parameter(Mandatory=$true)][string]$Method,
    [Parameter(Mandatory=$true)][string]$Uri,
    [Parameter()][hashtable]$Headers,
    [Parameter()][object]$Body
  )
  $h = @{ Authorization = "Bearer $script:AccessToken"; "Content-Type" = "application/json" }
  if ($Headers) { $Headers.GetEnumerator() | ForEach-Object { $h[$_.Name] = $_.Value } }
  if ($Body) {
    $json = if($Body -is [string]) { $Body } else { $Body | ConvertTo-Json -Depth 20 }
    return Invoke-RestMethod -Method $Method -Uri $Uri -Headers $h -Body $json
  } else {
    return Invoke-RestMethod -Method $Method -Uri $Uri -Headers $h
  }
}

Write-Host "Acquiring token..." -ForegroundColor Cyan
$script:AccessToken = Get-GraphToken -TenantId $TenantId -ClientId $ClientId -ClientSecret $ClientSecret

# 1) Resolve mailbox ids (MBX:...) for source and destination via users/{id}/settings/exchange
Write-Host "Resolving mailbox ids..." -ForegroundColor Cyan
$srcExchange = Invoke-GraphJson -Method GET -Uri "$graph/beta/users/$SourceUser/settings/exchange"
$dstExchange = Invoke-GraphJson -Method GET -Uri "$graph/beta/users/$DestUser/settings/exchange"
$srcMailboxId = $srcExchange.primaryMailboxId
$dstMailboxId = $dstExchange.primaryMailboxId

if ([string]::IsNullOrWhiteSpace($srcMailboxId) -or [string]::IsNullOrWhiteSpace($dstMailboxId)) {
  throw "Failed to resolve MBX ids. Ensure User.Read.All and admin consent are granted."
}
Write-Host "Source MBX: $srcMailboxId"
Write-Host "Dest   MBX: $dstMailboxId"

# 2) Export the source item (returns base64 FTS stream in value[0].data)
Write-Host "Exporting item from source mailbox..." -ForegroundColor Cyan
$exportBody = @{ itemIds = @($SourceItemId) }
$exportResp = Invoke-GraphJson -Method POST -Uri "$graph/beta/admin/exchange/mailboxes/$srcMailboxId/exportItems" -Body $exportBody
if (!$exportResp.value -or $exportResp.value.Count -lt 1) { throw "Export returned no data." }
$exported = $exportResp.value[0]
$ftsData  = $exported.data  # base64 FTS opaque stream

# 3) Find the destination folder id (Inbox) if not provided
if (-not $DestFolderId) {
  Write-Host "Resolving destination Inbox folder id..." -ForegroundColor Cyan
  # List top-level folders and find 'Inbox' by displayName (sample; you can pass DestFolderId to avoid localization issues)
  $folders = Invoke-GraphJson -Method GET -Uri "$graph/beta/admin/exchange/mailboxes/$dstMailboxId/folders`?$select=id,displayName"
  $inbox = $folders.value | Where-Object { $_.displayName -eq 'Inbox' } | Select-Object -First 1
  if (-not $inbox) { throw "Could not find Inbox in destination mailbox. Specify -DestFolderId explicitly." }
  $DestFolderId = $inbox.id
}
Write-Host "Dest FolderId: $DestFolderId"

# 4) Create an import session (returns pre-authenticated importUrl with expiry)
Write-Host "Creating import session..." -ForegroundColor Cyan
$importSession = Invoke-GraphJson -Method POST -Uri "$graph/beta/admin/exchange/mailboxes/$dstMailboxId/createImportSession"
$importUrl = $importSession.importUrl
if (-not $importUrl) { throw "Failed to get importUrl from createImportSession." }
Write-Host "Import URL acquired (expires $($importSession.expirationDateTime))"

# 5) Import the item into destination Inbox (Mode=create). IMPORTANT: No Authorization header for the importUrl.
Write-Host "Importing into destination Inbox..." -ForegroundColor Cyan
$importBody = @{
  FolderId = $DestFolderId
  Mode     = "create"
  Data     = $ftsData
}
$importJson = $importBody | ConvertTo-Json -Depth 10
# Post to the opaque outlook.office365.com URL directly
$importResp = Invoke-RestMethod -Method POST -Uri $importUrl -ContentType "application/json" -Body $importJson
Write-Host "Imported itemId: $($importResp.itemId)"
Write-Host "changeKey    : $($importResp.changeKey)"
